apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${VOL_NAME}
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce     
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: ${VOL_DIR}
